# Generated by Django 3.2.15 on 2022-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220812_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='code',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='tip',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
