# Generated by Django 4.1 on 2022-08-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220812_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tags_icons/'),
        ),
    ]
