# Generated by Django 4.1 on 2022-08-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/tags_icons/'),
        ),
    ]
