# Generated by Django 4.1 on 2022-08-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tip_rate_alter_tag_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='rate',
            new_name='rating',
        ),
    ]
